import type { Metadata } from "next";
import RevealSection from "@/components/ui/RevealSection";

export const metadata: Metadata = {
  title: "Privacy Policy | De Novo Law Firm",
  description: "Learn how De Novo Law Firm collects, uses, and protects your personal data when you visit our website.",
};

const definitions = [
  {
    term: "Account",
    desc: "means a unique account created for You to access our Service or parts of our Service.",
  },
  {
    term: "Firm",
    desc: '(referred to as either "the Firm", "We", "Us" or "Our" in this Agreement) refers to De Novo Law Firm, 3728, 10th cross, 13th B main road, Indira Nagar, Bangalore 560046.',
  },
  {
    term: "Cookies",
    desc: "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
  },
  {
    term: "Country",
    desc: "refers to: India",
  },
  {
    term: "Device",
    desc: "means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
  },
  {
    term: "Personal Data",
    desc: "is any information that relates to an identified or identifiable individual.",
  },
  {
    term: "Service",
    desc: "refers to the Website.",
  },
  {
    term: "Service Provider",
    desc: "means any natural or legal person who processes the data on behalf of the Firm. It refers to third-party companies or individuals employed by the Firm to facilitate the Service, to provide the Service on behalf of the Firm, to perform services related to the Service or to assist the Firm in analyzing how the Service is used.",
  },
  {
    term: "Third-party Social Media Service",
    desc: "refers to any website or any social network website through which a User can log in or create an account to use the Service.",
  },
  {
    term: "Usage Data",
    desc: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
  },
  {
    term: "Website",
    desc: "refers to De Novo, accessible from http://denovolawfirm.in/",
  },
  {
    term: "You",
    desc: "means the individual accessing or using the Service, or the Firm, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
  },
];

export default function PrivacyPage() {
  return (
    <div style={{ backgroundColor: "var(--color-bg)", minHeight: "100vh" }}>
      {/* ── HERO HEADER ── */}
      <section style={{ position: "relative", paddingTop: "11rem", paddingBottom: "5rem", overflow: "hidden" }}>
        <div className="site-container">
          <RevealSection>
            <p className="label-tag" style={{ marginBottom: "1.8rem" }}>Legal & Regulatory</p>
            <h1 className="font-serif" style={{ fontSize: "clamp(2.8rem, 6vw, 4.8rem)", color: "var(--color-text-primary)", lineHeight: 1.1, marginBottom: "2rem", fontWeight: 400 }}>
              Privacy <em className="font-serif" style={{ fontStyle: "italic", color: "var(--color-primary)", fontWeight: 400 }}>Policy</em>
            </h1>
            <p style={{ fontFamily: "var(--font-sans)", fontSize: "1.05rem", color: "var(--color-text-secondary)", maxWidth: "640px", lineHeight: 1.8 }}>
              Last updated: June 10, 2026. This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information.
            </p>
          </RevealSection>
        </div>
      </section>

      {/* ── CONTENT BODY ── */}
      <section style={{ padding: "3rem 0 8rem 0", backgroundColor: "#fff" }}>
        <div className="site-container">
          <div className="max-w-3xl mx-auto">
            <RevealSection>
              
              {/* SECTION: Interpretation and Definitions */}
              <div style={{ marginBottom: "4rem" }}>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Interpretation and Definitions
                </h2>
                
                <h3 className="font-sans font-bold text-sm text-[var(--color-text-primary)] uppercase tracking-wider mb-3">
                  Interpretation
                </h3>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-6">
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h3 className="font-sans font-bold text-sm text-[var(--color-text-primary)] uppercase tracking-wider mb-4">
                  Definitions
                </h3>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-6">
                  For the purposes of this Privacy Policy:
                </p>

                <div className="space-y-4 my-8">
                  {definitions.map((def) => (
                    <div 
                      key={def.term}
                      style={{ 
                        padding: "1.5rem", 
                        backgroundColor: "var(--color-bg)", 
                        borderLeft: "2px solid var(--color-primary)",
                        borderTop: "1px solid var(--color-border)",
                        borderRight: "1px solid var(--color-border)",
                        borderBottom: "1px solid var(--color-border)"
                      }}
                    >
                      <h4 className="font-sans font-bold text-xs uppercase tracking-wider text-[var(--color-primary)] mb-1">
                        {def.term}
                      </h4>
                      <p className="font-sans text-[13px] text-[var(--color-text-secondary)] leading-relaxed">
                        {def.desc}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* SECTION: Collecting and Using Your Personal Data */}
              <div style={{ marginBottom: "4rem" }}>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Collecting and Using Your Personal Data
                </h2>

                <h3 className="font-sans font-bold text-sm text-[var(--color-text-primary)] uppercase tracking-wider mb-4">
                  Types of Data Collected
                </h3>

                <h4 className="font-serif text-lg text-[var(--color-text-primary)] mb-3 font-normal">
                  Personal Data
                </h4>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="space-y-3 mb-6 pl-4">
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    Email address
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    First name and last name
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    Phone number
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    Address, State, Province, ZIP/Postal code, City
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    Usage Data
                  </li>
                </ul>

                <h4 className="font-serif text-lg text-[var(--color-text-primary)] mt-8 mb-3 font-normal">
                  Usage Data
                </h4>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  Usage Data is collected automatically when using the Service.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-6">
                  We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                </p>

                <h4 className="font-serif text-lg text-[var(--color-text-primary)] mt-8 mb-3 font-normal">
                  Tracking Technologies and Cookies
                </h4>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                </p>
                <ul className="space-y-4 mb-6 pl-4">
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] align-top">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] align-top">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read &quot;Where can I change the settings for disabling, or deleting local shared objects?&quot; available at <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_" target="_blank" rel="noopener noreferrer" className="text-[var(--color-primary)] hover:underline">Adobe Flash Support</a>.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] align-top">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Firm, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
                      </div>
                    </div>
                  </li>
                </ul>

                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-6">
                  Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-6">
                  We use both Session and Persistent Cookies for the purposes set out below:
                </p>

                {/* Cookies Cards Grid */}
                <div className="grid grid-cols-1 gap-6 my-8">
                  {/* Card 1 */}
                  <div style={{ padding: "1.8rem", backgroundColor: "var(--color-bg)", border: "1px solid var(--color-border)" }}>
                    <div style={{ display: "flex", justifyContent: "between", alignItems: "center", marginBottom: "1rem" }} className="flex justify-between items-center">
                      <h5 className="font-serif text-[15px] text-[var(--color-text-primary)] font-normal">Necessary / Essential Cookies</h5>
                      <span style={{ fontSize: "9px", letterSpacing: "0.1em", fontWeight: 700, padding: "0.2rem 0.5rem" }} className="bg-[var(--color-primary)]/10 text-[var(--color-primary)] uppercase rounded-sm">
                        Session
                      </span>
                    </div>
                    <p style={{ fontSize: "12px", color: "var(--color-text-muted)", marginBottom: "0.8rem" }}>Administered by: Us</p>
                    <p className="font-sans text-xs text-[var(--color-text-secondary)] leading-relaxed">
                      <strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                    </p>
                  </div>

                  {/* Card 2 */}
                  <div style={{ padding: "1.8rem", backgroundColor: "var(--color-bg)", border: "1px solid var(--color-border)" }}>
                    <div className="flex justify-between items-center mb-4" style={{ display: "flex", justifyContent: "between", alignItems: "center", marginBottom: "1rem" }}>
                      <h5 className="font-serif text-[15px] text-[var(--color-text-primary)] font-normal">Cookies Policy / Notice Acceptance Cookies</h5>
                      <span style={{ fontSize: "9px", letterSpacing: "0.1em", fontWeight: 700, padding: "0.2rem 0.5rem" }} className="bg-[var(--color-primary)]/10 text-[var(--color-primary)] uppercase rounded-sm">
                        Persistent
                      </span>
                    </div>
                    <p style={{ fontSize: "12px", color: "var(--color-text-muted)", marginBottom: "0.8rem" }}>Administered by: Us</p>
                    <p className="font-sans text-xs text-[var(--color-text-secondary)] leading-relaxed">
                      <strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.
                    </p>
                  </div>

                  {/* Card 3 */}
                  <div style={{ padding: "1.8rem", backgroundColor: "var(--color-bg)", border: "1px solid var(--color-border)" }}>
                    <div className="flex justify-between items-center mb-4" style={{ display: "flex", justifyContent: "between", alignItems: "center", marginBottom: "1rem" }}>
                      <h5 className="font-serif text-[15px] text-[var(--color-text-primary)] font-normal">Functionality Cookies</h5>
                      <span style={{ fontSize: "9px", letterSpacing: "0.1em", fontWeight: 700, padding: "0.2rem 0.5rem" }} className="bg-[var(--color-primary)]/10 text-[var(--color-primary)] uppercase rounded-sm">
                        Persistent
                      </span>
                    </div>
                    <p style={{ fontSize: "12px", color: "var(--color-text-muted)", marginBottom: "0.8rem" }}>Administered by: Us</p>
                    <p className="font-sans text-xs text-[var(--color-text-secondary)] leading-relaxed">
                      <strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                    </p>
                  </div>
                </div>

                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-6">
                  For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
                </p>
              </div>

              {/* SECTION: Use of Your Personal Data */}
              <div style={{ marginBottom: "4rem" }}>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Use of Your Personal Data
                </h2>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  The Firm may use Personal Data for the following purposes:
                </p>

                <ul className="space-y-4 mb-8 pl-4">
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>To provide and maintain our Service:</strong> including to monitor the usage of our Service.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>To provide You with news, special offers and general information:</strong> about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>To manage Your requests:</strong> To attend and manage Your requests to Us.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
                      </div>
                    </div>
                  </li>
                </ul>

                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  We may share Your personal information in the following situations:
                </p>
                <ul className="space-y-4 mb-6 pl-4">
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Firm assets, financing, or acquisition of all or a portion of Our business to another Firm.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent Firm and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.
                      </div>
                    </div>
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)]">
                    <div className="flex items-start">
                      <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 mt-2 flex-shrink-0" />
                      <div>
                        <strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.
                      </div>
                    </div>
                  </li>
                </ul>
              </div>

              {/* SECTION: Retention of Your Personal Data */}
              <div style={{ marginBottom: "4rem" }}>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Retention of Your Personal Data
                </h2>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  The Firm will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  The Firm will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                </p>
              </div>

              {/* SECTION: Transfer of Your Personal Data */}
              <div style={{ marginBottom: "4rem" }}>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Transfer of Your Personal Data
                </h2>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  Your information, including Personal Data, is processed at the Firm&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  The Firm will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
                </p>
              </div>

              {/* SECTION: Disclosure of Your Personal Data */}
              <div style={{ marginBottom: "4rem" }}>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Disclosure of Your Personal Data
                </h2>
                
                <h3 className="font-sans font-bold text-sm text-[var(--color-text-primary)] uppercase tracking-wider mb-3">
                  Business Transactions
                </h3>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-6">
                  If the Firm is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                </p>

                <h3 className="font-sans font-bold text-sm text-[var(--color-text-primary)] uppercase tracking-wider mb-3">
                  Law enforcement
                </h3>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-6">
                  Under certain circumstances, the Firm may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                </p>

                <h3 className="font-sans font-bold text-sm text-[var(--color-text-primary)] uppercase tracking-wider mb-4">
                  Other legal requirements
                </h3>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  The Firm may disclose Your Personal Data in the good faith belief that such action is necessary to:
                </p>
                <ul className="space-y-3 mb-6 pl-4">
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    Comply with a legal obligation
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    Protect and defend the rights or property of the Firm
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    Prevent or investigate possible wrongdoing in connection with the Service
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    Protect the personal safety of Users of the Service or the public
                  </li>
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    Protect against legal liability
                  </li>
                </ul>
              </div>

              {/* SECTION: Security of Your Personal Data */}
              <div style={{ marginBottom: "4rem" }}>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Security of Your Personal Data
                </h2>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
              </div>

              {/* SECTION: Links to Other Websites */}
              <div style={{ marginBottom: "4rem" }}>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Links to Other Websites
                </h2>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
              </div>

              {/* SECTION: Changes to this Privacy Policy */}
              <div style={{ marginBottom: "4rem" }}>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Changes to this Privacy Policy
                </h2>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
                </p>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
              </div>

              {/* SECTION: Contact Us */}
              <div>
                <h2 className="font-serif text-2xl mb-6 text-[var(--color-primary)] border-b border-[var(--color-border)] pb-3 font-normal">
                  Contact Us
                </h2>
                <p className="font-sans text-sm text-[var(--color-text-secondary)] leading-relaxed mb-4">
                  If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <ul className="space-y-3 pl-4">
                  <li className="font-sans text-sm text-[var(--color-text-secondary)] flex items-center">
                    <span className="inline-block w-1.5 h-1.5 bg-[var(--color-primary)] rounded-full mr-3 flex-shrink-0" />
                    By email:&nbsp;
                    <a href="mailto:harsit@denovolawfirm.in" className="text-[var(--color-primary)] hover:underline font-semibold">
                      harsit@denovolawfirm.in
                    </a>
                  </li>
                </ul>
              </div>

            </RevealSection>
          </div>
        </div>
      </section>
    </div>
  );
}
